### ISSUE TITLE
First reboot ends in UEFI Shell

### ISSUE THREAD

**Issue by ravenclaw78** [Sithuk/ubuntu-server-zfsbootmenu#1]
Goal is to install a 22.04 server with a mirror root.

As the server has not arrived yet, I try to do a dry run in a kvm.

Starting with 21.04, 21.10 and the new 22.04 ubuntu live image, the vm always end up in the uefi shell after first boot.

This is the uefi part of its configuration:
```
  <os>
    <type arch="x86_64" machine="pc-q35-6.0">hvm</type>
    <loader readonly="yes" type="pflash">/usr/share/OVMF/OVMF_CODE_4M.ms.fd</loader>
    <nvram>/var/lib/libvirt/qemu/nvram/test_VARS.fd</nvram>
  </os>
```
Here are the values I changed:
```
ubuntuver="jammy" #Ubuntu release to install. "hirsute" (21.04). "impish" (21.10). "jammy" (22.04).
distro_variant="server" #Ubuntu variant to install. "server" (Ubuntu server; cli only.) "desktop" (Default Ubuntu desktop install). "kubuntu" (KDE plasma desktop variant). "xubuntu" (Xfce desktop variant). "MATE" (MATE desktop variant).
user="test" #Username for new install.
PASSWORD="testtest" #Password for user in new install.
hostname="testserver" #Name to identify the new install on the network. An underscore is DNS non-compliant.
zfspassword="testtest" #Password for root pool and data pool. Minimum 8 characters.

topology_root="mirror" #single, mirror, raidz1, raidz2, or raidz3 topology on root pool.
disks_root="2" #Number of disks in array for root pool. Not used with single topology.
```

What am I doing wrong?

**Comment by Sithuk** [comment]
Hi ravenclaw,

The script variables you posted look ok. I'm not familiar with kvm unfortunately, so can't be much help with its setup. 

Please could you provide the script installation log? That would let me check whether anything went wrong during the installation.

**Comment by ravenclaw78** [comment]
To get it this far with kvm, I had to manually add a serial number to each virtual disk in xml, so your script is able to find them under /dev/disk/by-id. But I don't think that this has something to do with the shell issue. [solution](https://github.com/systemd/systemd/issues/17670)

This time I bootet ubuntu 22.04 in EN (instead of DE), checked out current version, and started the initial run. No changes at all. Selected the first disk.
After reboot i get this:
![uefi_shell](https://user-images.githubusercontent.com/4131000/164993057-f568570b-9e20-4d59-9987-f4ea3e5270ad.png)

Here is the log from this run:
[ubuntu_setup_zfs_root.log](https://github.com/Sithuk/ubuntu-server-zfsbootmenu/files/8550376/ubuntu_setup_zfs_root.log)

Thank you for your time.

**Comment by Sithuk** [comment]
I can't see anything obviously wrong in the log. Are you able to manually select the efi file to boot from?

**Comment by ravenclaw78** [comment]
Yesterday I tried installing in VirtualBox, and it worked flawless (only tested if it could boot, not further).
The only difference I could spot was sda(virtualBox) vs vda(kvm).
So I tried kvm with a sata disk instead of a virtio disk, but this did not work.

This is my first encounter with the uefi shell, could you give me a hint/link on how to boot the efi file?

**Comment by Sithuk** [comment]
I’m glad the script worked in Virtualbox. Hopefully you can test on your hardware server when it arrives too. 

For your kvm issue, are you able to select the efi file from a boot menu as part of the kvm boot sequence? Virtualbox has an option to press F12 during boot to select boot device. Does kvm have something similar?

**Comment by ravenclaw78** [comment]
Seems refind crashes freeing the banner image. [link](https://sourceforge.net/p/refind/discussion/general/thread/4dfcdfdd16/)

Adding ```hideui banner``` to refind.conf solved the problem.
![grafik](https://user-images.githubusercontent.com/4131000/165378824-8f0d8d75-b7ca-46ca-adfb-5793cdb7d1cf.png)


At line 757 of your script I simply added:
```
echo hideui banner >>/boot/efi/EFI/refind/refind.conf
```

But I still have to manually boot it via efi shell.

**Comment by Sithuk** [comment]
That's good news. I'm glad you finally got the script to work with kvm. Thank you for posting the solution. If you find the solution to having to manually boot the kvm VM each time, please post that here too.
