### ISSUE TITLE
VirtIO-backed drives are not available for selection during initial setup

### ISSUE THREAD

**Issue by UntouchedWagons** [Sithuk/ubuntu-server-zfsbootmenu#14]
I created a VM on my Proxmox machine and loaded the Ubuntu 22.04 desktop ISO. I installed git, set the variables as instructed and ran the initial portion of the script. However I could not choose the virtio-backed drive because it doesn't show up in /dev/disk/by-id, it only appears as /dev/vda (additional drives would be /dev/vdb and so on).

**Comment by Sithuk** [comment]
It seems that virtio doesn't create the block device symlinks. I found an article covering the issue. The author also provides a fix that you could try. See below.

[Adding a serial through Proxmox](https://www.osso.nl/blog/proxmox-virtio-blk-disk-by-id/#adding-a-serial-through-proxmox)
Instead, we can hand-hack the Proxmox VE QEMU configuration file and add a (custom 20 bytes) ,serial=MY_SERIAL parameter to the disk configuration.

**Comment by Sithuk** [comment]
Did you try the fix for virtio set out in the blog post above? Did it work for you?

**Comment by UntouchedWagons** [comment]
Yeah I got around to trying adding a custom serial and it worked, although the script didn't copy itself to /root in the new install
