### ISSUE TITLE
Scripts gets stuck updating mirrors

### ISSUE THREAD

**Issue by Anonymo** [Sithuk/ubuntu-server-zfsbootmenu#15]
Ubuntu 22.04.1 live iso, did desktop install.

Script stuck at Ign:26 https://dal.mirrors.clouvider...

**Comment by Sithuk** [comment]
The link you posted doesn’t work? Is it to a log file?

**Comment by Anonymo** [comment]
> The link you posted doesn’t work? Is it to a log file?

Sorry, it was late, and I was trying to figure out why it got stuck on this.  This is the last line it got stuck on, but it's truncated.  Is there a place to grab a log at if something fails?  This was during the first step after configuring and running the script, when it's updating the mirrors to use.  The script did work the previous time I used it on 22.04.0.

**Comment by Sithuk** [comment]
There should be a log in /var/log of the new installation, unless you changed the log location variable to somewhere else.

**Comment by Sithuk** [comment]
I've just pushed an update to improve the code that identifies which ubuntu mirror to use. Could you test and report back if it corrects the problem you had?

**Comment by Anonymo** [comment]
> I've just pushed an update to improve the code that identifies which ubuntu mirror to use. Could you test and report back if it corrects the problem you had?

I'll give it a shot soon.  Sorry about not trying it again, but I've had a series of bad events the last few weeks.  Got completely hacked on my Gmail, Amazon, etc. Then my car was flooded with water in the engine.  But should be back on track by next weekend.

**Comment by Sithuk** [comment]
Sorry to hear about your troubles and best of luck for getting back on track. Let me know if you have any further problems with the script.
