### ISSUE TITLE
How to restart after Ctrl+ C?

### ISSUE THREAD

**Issue by mcamou** [Sithuk/ubuntu-server-zfsbootmenu#19]
Hello and thanks for building this project.

I've had to Ctrl+C because I noticed in the middle of the run that I'd misconfigured something. When restarting I got an error stating that rpool was mounted. I tried `zpool export rpool` and the system said that rpool is busy. `lsof` shows no files using the directory, but `zfs umount -a` also says that it's busy. The only option I found was rebooting. Any ideas?

**Comment by Sithuk** [comment]
I haven't had much success in exporting a mounted pool even with the force flag on zpool export. You did what I would have done which is to re-boot and start again.
