### ISSUE TITLE
Connecting to wifi in postinstall

### ISSUE THREAD

**Issue by mcamou** [Sithuk/ubuntu-server-zfsbootmenu#21]
How do I connect to WiFi after rebooting to do the postinstall? I am installing Kubuntu, but it seems that NetworkManager is installed/configured only after installing the distro, and I need WiFi to install the distro itself.

**Comment by Sithuk** [comment]
You shouldn't need wifi to carry out the postreboot install part of the script. The ethernet connection should work fine. As you note, wifi isn't setup at that stage. Please can you test to confirm?

**Comment by mcamou** [comment]
My issue is that I don't have Ethernet on my laptop at the moment, my only connection to the internet is via WiFi. Any ideas?

**Comment by mcamou** [comment]
Now that I think about it, would it be possible to run postreboot in a chroot while still in the live CD environment? I assume that that is how most distros do it.

**Comment by Sithuk** [comment]
You could edit the netplan config file created in the initial part of the script to add your wifi details prior to the reboot. Or edit the script to include the details. Then the wifi should be present post reboot.

The config file is in /etc/netplan of your chroot environment. You could try editing the file to reflect the following. Remember that yaml config files are sensitive to the number of spaces of each indent. You'll need to replace the variable names with your actual interface name, wifi name and wifi password. You might need to do additional steps but hopefully this is enough to point you in the right direction.

network:
  version: 2
  ethernets:
    $ethernetinterface:
      dhcp4: yes
  wifis:
    $wifiinterface:
      dhcp4: yes
      access-points:
        "$nameofwifi":
          password: "$wifipassword"

**Comment by Sithuk** [comment]
Or you could try to install NetworkManager in a chroot environment after the intial part of the script is complete, but prior to the first reboot.

**Comment by mcamou** [comment]
Just FYI, I did as I suggested and ran postreboot in a chroot. Everything seems to have worked well, the system booted and all works as expected. It might be a good idea to do a single-step process, everything in the live CD environment, I'm not sure what the downsides would be.

**Comment by Sithuk** [comment]
The initial approach to the script was to follow rlaager's zfs on root guide on the Openzfs Documentation website (linked in the readme). Rlaager splits the install procedure across a reboot. Please let me know if you experience any issues with your install.

**Comment by mcamou** [comment]
Everything is still working fine, I haven't noticed any issues (which doesn't mean that there aren't any, just that I haven't noticed them). It might be a good idea to add an experimental option to run the second phase in a live CD environment chroot.

**Comment by Sithuk** [comment]
Hi mcamou, I've revised the script to carry out the installation in a single step from the live CD environment. There is no longer a need to reboot to continue the installation. Are you able to test the revised script and let me know if it works for you?

**Comment by mcamou** [comment]
Hi Sithuk, I unfortunately don't have a box where I can test it ATM. I did the previous installation in my main work laptop.

**Comment by Sithuk** [comment]
No problem. Maybe next time.
