### ISSUE TITLE
Kubuntu 23.04 E: Release signed by unknown key (key id 40976EAF437D05B5)

### ISSUE THREAD

**Issue by alci63** [Sithuk/ubuntu-server-zfsbootmenu#31]
Hi,

I am testing the script in a VM, trying to install Kubuntu 23.04 (lucid). Latest comments suggest this should work, even if 22.04 is the main tested target.
However, I get an error when debbootstrap kicks in: E: Release signed by unknown key (key id 40976EAF437D05B5)

Here is the full log:

Setting up zfsutils-linux (2.1.9-2ubuntu1.1) ...
zfs-import-scan.service is a disabled or a static unit, not starting it.
Setting up zfs-initramfs (2.1.9-2ubuntu1.1) ...
Setting up zfs-zed (2.1.9-2ubuntu1.1) ...
Processing triggers for libc-bin (2.37-0ubuntu2) ...
Processing triggers for man-db (2.11.2-1) ...
Processing triggers for initramfs-tools (0.142ubuntu2) ...
update-initramfs is disabled since running on read-only media
Clearing partition table on disk ata-VBOX_HARDDISK_VB32f867bd-189ef66f.
Creating new GPT entries in memory.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Clearing partition table on disk ata-VBOX_HARDDISK_VBfa27f83c-617632d5.
Creating new GPT entries in memory.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Creating partitions on disk ata-VBOX_HARDDISK_VB32f867bd-189ef66f.
Creating new GPT entries in memory.
The operation has completed successfully.
The operation has completed successfully.
The operation has completed successfully.
Creating partitions on disk ata-VBOX_HARDDISK_VBfa27f83c-617632d5.
Creating new GPT entries in memory.
The operation has completed successfully.
The operation has completed successfully.
The operation has completed successfully.
I: Retrieving InRelease 
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
E: Release signed by unknown key (key id 40976EAF437D05B5)
   The specified keyring /usr/share/keyrings/ubuntu-archive-keyring.gpg may be incorrect or out of date.
   You can find the latest Debian release key at https://ftp-master.debian.org/keys.html

**Comment by Sithuk** [comment]
You referenced "Kubuntu 23.04 (lucid)" in your first sentence. But lucid was the codename for Ubuntu 10.04, not 23.04. Ubuntu 23.04 has codename lunar. I tested the script with "lucid" and got the same keyring error. Using the correct codename "lunar" works fine.

**Comment by alci63** [comment]
Sorry for my mistake... and thanks for taking the time to reply.
Well, you're right, test in a VM before going live :-)
And many thanks for you script, also.
