### ISSUE TITLE
swapon -a fails periodically due to running too quickly, short pause reliably fixes

### ISSUE THREAD

**Issue by KyleCo76** [Sithuk/ubuntu-server-zfsbootmenu#33]
Awesome script! The only problem I've been running into is that swapon -a has been failing at line 1179 saying no such file found. I can indeed find this file after the script errors out. I tried placing a 'sleep 2' between echo /dev/disk/by-uuid/\${blkid_part2} none swap defaults 0 0 >> /etc/fstab and swapon -a and this has worked flawlessly everytime. It could probably be less than 2, I chose a number for my testing.

This is running in Proxmox 7.4 on a Ryzen 9 7950x. When the vm is limited to about 12 threads, it's hit or miss if the swapon fails, mostly failing. With all 32 threads assessable to the vm, it failed 15 times in a row. With the 'sleep 2' it's worked 6 times so far. 

Very minor issue, but wanted to let you know. Thank you very much for the work on this, it's been a lifesaver!

**Comment by Sithuk** [comment]
Thank you for the feedback. I've added your suggested change in the following commit.
https://github.com/Sithuk/ubuntu-server-zfsbootmenu/commit/350f4bea86074db2d4ebe079ba0b9bd3f321d382
