### ISSUE TITLE
installation failure with : efibootmgr hp prolient dl360

### ISSUE THREAD

**Issue by Lautreck** [Sithuk/ubuntu-server-zfsbootmenu#38]
Hello,
when i try to use the script to install ubuntu 20.04 i get a error, "efibootmgr : command not found "
I'm trying to install on a hp gen 10 prolient dl360

you have access to my log and the setup file.

EDIT :
needed to install the package : sudo apt-get install efibootmgr

**Comment by Sithuk** [comment]
The script is for Ubuntu 22.04. I haven't tested it with 20.04. I'm glad you've found the problem. I'll test the script with 22.04 using your drive setup variables to check there isn't a problem.

I had a look at the log and script file you sent. Why have you decided on a raidz1 config rather than a mirror config? You have two drives, so you will have a parity calculation overhead with no gain in resilience? That is, you can lose one drive without data loss. The same as a mirror. Except with the mirror, there are no parity calculations.

**Comment by Lautreck** [comment]
Hello,
yeah i fucked up i was meaning 22.04, my bad.
i do need to try to install the 20.04 version, i was trying the 22.04 to avoid as much as possible problems.
For raidz1 or mirror, i was just checking if this was what was fucking up my installation, just trying stuff at random.
i'm using mirror now.

I managed to finalize an installation but the pool didn't work apparently.
when booting it tell me in the zfsbootmenu that it's unable to import pool.

![photo_2024-03-18_11-44-30](https://github.com/Sithuk/ubuntu-server-zfsbootmenu/assets/8440795/331b593c-895a-4d87-99fe-393e3abbb85f)

i'm trying an install again rn with 20.04

**Comment by Sithuk** [comment]
I haven't tested the current script with 20.04. Have you tried edifus' earlier fork of my script that is for 20.04?

https://github.com/edifus/ubuntu-server-zfsbootmenu

**Comment by Lautreck** [comment]
[ubuntu_setup_zfs_root.log](https://github.com/Sithuk/ubuntu-server-zfsbootmenu/files/14636034/ubuntu_setup_zfs_root.log)

while trying to install 20.04 it give me a error with bsdextrautils.

the instalation with 22.04 perfectly went through

**Comment by Lautreck** [comment]
> I haven't tested the current script with 20.04. Have you tried edifus' earlier fork of my script that is for 20.04?
> 
> https://github.com/edifus/ubuntu-server-zfsbootmenu

I wasn't aware of it thank you.
i wil try this as well

**Comment by Sithuk** [comment]
Closing the issue as you've confirmed the installation worked with 22.04. What changed that it worked now but didn't work before. Did you have internet connection problems that meant a package wasn't downloaded during the install process?

**Comment by Lautreck** [comment]
> Closing the issue as you've confirmed the installation worked with 22.04. What changed that it worked now but didn't work before. Did you have internet connection problems that meant a package wasn't downloaded during the install process?

i am not aware of why the pool corrupted during my first installation.
there was no error given at the end.

thanks for the help
