### ISSUE TITLE
After running initial script install - dropping into grub shell / Ubuntu 22.04 Raid-Z1

### ISSUE THREAD

**Issue by jak83A** [Sithuk/ubuntu-server-zfsbootmenu#5]
The script ended with:

Test Summary Report
-------------------
t/32.cyclic-refs.t       (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=43, Tests=7434, 15 wallclock secs ( 1.51 usr  0.16 sys + 11.93 cusr  1.08 csys = 14.68 CPU)
Result: FAIL
Failed 1/43 test programs. 0/7434 subtests failed.
make: *** [Makefile:1007: test_dynamic] Error 255
  TINITA/YAML-PP-0.034.tar.gz
one dependency not OK (Test::Warn); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports TINITA/YAML-PP-0.034.tar.gz
+ rm -rf /root/.cpan/build
+ update-initramfs -k all -c
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "de_DE.UTF-8",
	LC_MONETARY = "de_DE.UTF-8",
	LC_ADDRESS = "de_DE.UTF-8",
	LC_TELEPHONE = "de_DE.UTF-8",
	LC_NAME = "de_DE.UTF-8",
	LC_MEASUREMENT = "de_DE.UTF-8",
	LC_IDENTIFICATION = "de_DE.UTF-8",
	LC_NUMERIC = "de_DE.UTF-8",
	LC_PAPER = "de_DE.UTF-8",
	LANG = "de_DE.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
update-initramfs: Generating /boot/initrd.img-5.15.0-46-generic
W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
+ generate-zbm
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "de_DE.UTF-8",
	LC_NAME = "de_DE.UTF-8",
	LC_MONETARY = "de_DE.UTF-8",
	LC_PAPER = "de_DE.UTF-8",
	LC_IDENTIFICATION = "de_DE.UTF-8",
	LC_TELEPHONE = "de_DE.UTF-8",
	LC_MEASUREMENT = "de_DE.UTF-8",
	LC_TIME = "de_DE.UTF-8",
	LC_NUMERIC = "de_DE.UTF-8",
	LANG = "de_DE.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't locate YAML/PP.pm in @INC (you may need to install the YAML::PP module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/bin/generate-zbm line 27.
BEGIN failed--compilation aborted at /usr/bin/generate-zbm line 27.
+ cat
main: line 73: /boot/efi/EFI/ubuntu/refind_linux.conf: No such file or directory
+ '[' no = no ']'
+ sed -i 's,ro quiet,ro,' /boot/efi/EFI/ubuntu/refind_linux.conf
sed: can't read /boot/efi/EFI/ubuntu/refind_linux.conf: No such file or directory

**Comment by jak83A** [comment]
sure, i will do it again and share it - pls instruct me in details what log do you like - so we get the info for you.

**Comment by Sithuk** [comment]
There are two variables that control the log filename and its location. These are set in the script with the following variables.
install_log="ubuntu_setup_zfs_root.log" #Installation log filename.
log_loc="/var/log" #Installation log location.

The default is /var/log/ubuntu_setup_zfs_root.log

**Comment by Sithuk** [comment]
Ideally, you could re-run the install with the "#set -x" line uncommented. That would log all the executed commands and provide more debug info. That is, replace "#set -x" with "set -x" before you execute the script.

**Comment by Sithuk** [comment]
I just did a test install for a raidz1 configuration in Virtualbox and it worked fine. There was the following message during boot:
"mtd device must be supplied (device name is empty)"
The message is related to a bug in upstream that doesn't seem to affect the system and has already been patched in the development version.
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1981622
Were you able to locate the log file?

**Comment by jak83A** [comment]
Yep, got the logfile, but it's too big to post here, can you send me your email address or any other destination i could send it to?

**Comment by jak83A** [comment]
ok, her's one link [https://gofile.io/d/mw9ALc](url)

**Comment by jak83A** [comment]
This time however it's different ... it opens the ubuntu boot, attempts to boot ... 
but then ...

`Volume group "vgubuntu" not found
Cannot process volume group vgbuntu
cryptsetup: Waiting for encrypted source device UUID=be720e85-6ef4-4496-b159-e98d1b618efa...
Volume group "vgubuntu" not found
Cannot process volume group vgbuntu
cryptsetup: Waiting for encrypted source device UUID=be720e85-6ef4-4496-b159-e98d1b618efa...
Gave up waiting for root filesystem device. Common problems:
- Boot args (cat /proc/cmdline)
-  Check rootdelay= (did the system wait long enough?)
- MIssing modules (cat/proc/modules; ls /dev)`
- ALERT /dev/mappper/vgubuntu-root does not exist. Dropping to a shell!'

Then it drops to initramfs...

**Comment by Sithuk** [comment]
I think you need to set the locale variable to the one valid for your system (German?).

The variable is set here in the variables section of the script:
locale="en_GB.UTF-8" #New install language setting.

It looks like you need to set it to:
locale="de_DE.UTF-8"

Could you try that to see if it clears up all the PERL locale warnings?

**Comment by jak83A** [comment]
I tried... i also changed time to "Europe/Berlin" , now i am stuck on:

Holen:35 http://ftp.uni-mainz.de/ubuntu jammy-updates/main amd64 Packages [502 kB]


was the change of timezone a mistake?

**Comment by Sithuk** [comment]
The timezone shouldn't have any impact on the package retrieval. I've found sometimes apt just times out on a server. I usually just try again when that happens. Are you no longer getting the perl locale errors?

**Comment by jak83A** [comment]
now it ran through almost...

and asks this:

`cryptsetup ist schon die neueste Version (2:2.4.3-1ubuntu1.1).
cryptsetup wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 39 nicht aktualisiert.
+ mdadm --create /dev/md0 --metadata=1.2 --level=5 --raid-devices=3 /dev/disk/by-id/nvme-eui.6479a74f7f003906-part2 /dev/disk/by-id/nvme-eui.6479a74f7f00482b-part2 /dev/disk/by-id/nvme-eui.6479a74f7f0050f9-part2
mdadm: /dev/disk/by-id/nvme-eui.6479a74f7f003906-part2 appears to be part of a raid array:
       level=raid5 devices=3 ctime=Mon Aug 15 10:48:29 2022
mdadm: /dev/disk/by-id/nvme-eui.6479a74f7f00482b-part2 appears to contain an ext2fs file system
       size=1750016K  mtime=Thu Aug 11 18:20:48 2022
mdadm: /dev/disk/by-id/nvme-eui.6479a74f7f00482b-part2 appears to be part of a raid array:
       level=raid5 devices=3 ctime=Mon Aug 15 10:48:29 2022
mdadm: /dev/disk/by-id/nvme-eui.6479a74f7f0050f9-part2 appears to be part of a raid array:
       level=raid5 devices=3 ctime=Mon Aug 15 10:48:29 2022
Continue creating array? 
Continue creating array? (y/n) 
`

**Comment by Sithuk** [comment]
Looks like the md array wasn't cleared when re-running the script. You'll need to cancel the script, then stop the array, then re-run the script. 

Please see rlaager's guide step 2, part 2 here:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2022.04%20Root%20on%20ZFS.html#

Extract below.
----
# See if one or more MD arrays are active:
cat /proc/mdstat
# If so, stop them (replace ``md0`` as required):
mdadm --stop /dev/md0
----

I didn't have the problem in testing, but I may need to add these steps to the script. Please try it and let me know if it works.

**Comment by jak83A** [comment]
i stopped the script - after cat /proc/mdstat it's like this:


`mdadm: cannot open /dev/md0: No such file or directory
root@ubuntu:~/ubuntu-server-zfsbootmenu# cat /proc/mdstat
Personalities : 
unused devices: <none>
`

so should i just rerun the script or do something else before?

**Comment by Sithuk** [comment]
Looks ok. If you can, I would restart the computer before running the script again as a pre-caution. However, it looks like there are no md arrays present, so you should be able to go ahead and re-run the script.

**Comment by jak83A** [comment]
I did delete all partitions in gparted, then restarted the machine and tried again... 

Here's the new log of initial install: [https://gofile.io/d/MzFNUj](url)

After rebooting i end up at the grub> minimal bash.

**Comment by Sithuk** [comment]
I'm getting a security alert when I try to download from gofile:
"NET::ERR_CERT_COMMON_NAME_INVALID".

Could you upload the file somewhere else?

**Comment by jak83A** [comment]
sure,

https://skytransfer.hns.siasky.net/#/v2/0b3a72fa50bd7fc70cd2e887200a8b7189771f24a881f26f08fbf097ad0ba33f/00e0c1a9322558ce86ac2810dfa3718b335591039bb9539c18d21a402c9f86f61e90b9cb2324398184ffed82b6cd892f011031d29bb31a1de4a2da77a0e51618

**Comment by Sithuk** [comment]
It looks like the script initial installation completed ok.

Is your system set to boot in UEFI instead of a legacy BIOS mode? If it is set to boot in UEFI mode, are you able to select the efi image file to boot from within your UEFI? You may have been dropped to an UEFI interactive shell at boot because your system can't find the efi file to load rEFInd. The efi file may need to be selected in the UEFI.

"After rebooting i end up at the grub> minimal bash."
Do you see a "Shell>" prompt? If so, that is the UEFI interactive shell.

**Comment by jak83A** [comment]
no , this is not the EFI shell, system works in EFI, then comes to refind boot screen then ... to "grub>" shell

**Comment by Sithuk** [comment]
Does the prompt say ‘grub>’? The script doesn’t install grub, so that would be odd. 

What screen do you see after the refind boot screen? Do you get the zfsbootmenu start screen where it offers an option to either enter the zfsbootmenu menu or to proceed to boot the default option? There would be a timer ticking down.

You’re not at the zfsbootmenu screen to enter the rpool password are you?

**Comment by Sithuk** [comment]
Do you seen the screen shown in the first image on the following site.
https://www.linuxfoundation.org/blog/classic-sysadmin-how-to-rescue-a-non-booting-grub-2-on-linux/

**Comment by Sithuk** [comment]
Your install log doesn't indicate that grub was installed. Is your system trying to boot off one of your other drives?

**Comment by jak83A** [comment]
I have only 4x NVMe drives which i have removed all partitions from prior to running the script (where i used 3x of them, as i wanted later to assign the 4th one as hotspare to the rpool). 

Btw, is there any option to assign HS to the pool in your script?

**Comment by Sithuk** [comment]
There isn’t an option to add a hot spare in the script. 

I can see each nvme drive has two disk ID entries in your install log. But the options you selected seemed to work. I wrongly thought the Seagate Firecuda was a different drive to the nvme. You shouldnt get two disk ID options for a single drive so my code might need to be fixed. I wonder if the wrong disk ids are being used. If you try the Seagate Firecuda menu options to select disk id what happens?

**Comment by Sithuk** [comment]
Then again, rEFInd is loading at boot, so drive IDs must be ok. I’m still puzzled where grub is coming from.

**Comment by jak83A** [comment]
ok'll try to select "Seagate..."

**Comment by jak83A** [comment]
again this is asked... how come? 

say yes or no?


Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
mdadm ist schon die neueste Version (4.2-0ubuntu1).
mdadm wurde als manuell installiert festgelegt.
cryptsetup ist schon die neueste Version (2:2.4.3-1ubuntu1.1).
cryptsetup wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 39 nicht aktualisiert.
+ mdadm --create /dev/md0 --metadata=1.2 --level=5 --raid-devices=3 /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part2 /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part2 /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part2
mdadm: /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part2 appears to contain an ext2fs file system
       size=1750016K  mtime=Thu Aug 11 18:20:48 2022
mdadm: /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part2 appears to be part of a raid array:
       level=raid5 devices=3 ctime=Tue Aug 16 09:54:07 2022
mdadm: /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part2 appears to be part of a raid array:
       level=raid5 devices=3 ctime=Tue Aug 16 09:54:07 2022
mdadm: /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part2 appears to be part of a raid array:
       level=raid5 devices=3 ctime=Tue Aug 16 09:54:07 2022
Continue creating array?

**Comment by Sithuk** [comment]
Best try a reboot to clear any temporary settings. Otherwise you could get a conflict.

**Comment by jak83A** [comment]
But i get this even after reboot... i don't know how to get rid of this message...

**Comment by Sithuk** [comment]
Does stopping the array work? (See my response from 2 days ago above: "cat /proc/mdstat" to see if there are any arrays, then "mdadm --stop /dev/md0".

**Comment by Sithuk** [comment]
I'm concerned that the wrong Disk ID may being used too. Could you paste the results of the following "ls -la /dev/disk/by-id" ?

**Comment by jak83A** [comment]
"mdadm --stop /dev/md0" > no such file or directory....

**Comment by Sithuk** [comment]
And it still says there is an array when you try to run the script? Try just saying yes then to that mdadm prompt.

I'm concerned that the wrong Disk ID may being used too. Could you paste the results of the following "ls -la /dev/disk/by-id" ?

**Comment by jak83A** [comment]
the script stops at:

cannot resolve path '/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part3'

-------------
**ls -la /dev/disk/by-id** (after script execution halted by above error):

insgesamt 0
drwxr-xr-x 2 root root 580 Aug 17 14:05 .
drwxr-xr-x 8 root root 160 Aug 17 14:00 ..
lrwxrwxrwx 1 root root   9 Aug 17 14:05 md-name-ubuntu:0 -> ../../md0
lrwxrwxrwx 1 root root   9 Aug 17 14:05 md-uuid-0249b143:84bdca94:1b3783c8:3075135b -> ../../md0
lrwxrwxrwx 1 root root  13 Aug 17 14:05 nvme-eui.6479a74f7f003906 -> ../../nvme2n1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-eui.6479a74f7f003906-part1 -> ../../nvme2n1p1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-eui.6479a74f7f003906-part2 -> ../../nvme2n1p2
lrwxrwxrwx 1 root root  13 Aug 17 14:05 nvme-eui.6479a74f7f00482b -> ../../nvme0n1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-eui.6479a74f7f00482b-part1 -> ../../nvme0n1p1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-eui.6479a74f7f00482b-part2 -> ../../nvme0n1p2
lrwxrwxrwx 1 root root  13 Aug 17 14:01 nvme-eui.6479a74f7f004f4c -> ../../nvme3n1
lrwxrwxrwx 1 root root  13 Aug 17 14:05 nvme-eui.6479a74f7f0050f9 -> ../../nvme1n1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-eui.6479a74f7f0050f9-part1 -> ../../nvme1n1p1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-eui.6479a74f7f0050f9-part2 -> ../../nvme1n1p2
lrwxrwxrwx 1 root root  13 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9 -> ../../nvme1n1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part1 -> ../../nvme1n1p1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part2 -> ../../nvme1n1p2
lrwxrwxrwx 1 root root  13 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T -> ../../nvme2n1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part1 -> ../../nvme2n1p1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part2 -> ../../nvme2n1p2
lrwxrwxrwx 1 root root  13 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM -> ../../nvme0n1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part1 -> ../../nvme0n1p1
lrwxrwxrwx 1 root root  15 Aug 17 14:05 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part2 -> ../../nvme0n1p2
lrwxrwxrwx 1 root root  13 Aug 17 14:01 nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02JWA -> ../../nvme3n1
lrwxrwxrwx 1 root root   9 Aug 17 14:01 usb-Intenso_Speed_Line_21071356610015-0:0 -> ../../sda
lrwxrwxrwx 1 root root  10 Aug 17 14:01 usb-Intenso_Speed_Line_21071356610015-0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  10 Aug 17 14:01 usb-Intenso_Speed_Line_21071356610015-0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  10 Aug 17 14:01 usb-Intenso_Speed_Line_21071356610015-0:0-part3 -> ../../sda3
lrwxrwxrwx 1 root root  10 Aug 17 14:01 usb-Intenso_Speed_Line_21071356610015-0:0-part4 -> ../../sda4

**Comment by Sithuk** [comment]
Either disk id should work. But stick with the nguid identifiers as that did work (the eui ones). I’d try running the script again and select the eui disk ids. If you get the md array error, then reboot and try again. 

If you can get to that “grub>” prompt, try getting some info using “ls” or other basic commands to explore the filesystem that you boot into. Or you can enter “exit” and see what happens.

**Comment by jak83A** [comment]
this should be the problem:


The operation has completed successfully.
+ sgdisk -n3:0:0 -t3:BF00 /dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
+ IFS=
+ read -r diskidnum
+ sleep 2
+ debootstrap_createzfspools_Func
+ create_rpool_Func
+ zpool_create_temp=/tmp/rpool_creation.sh
+ cat
+ '[' -n XiaoSon#2020 ']'
+ echo '-O encryption=aes-256-gcm -O keylocation=prompt -O keyformat=passphrase \'
+ echo '-O mountpoint=/ -R /mnt/ub_server \'
+ case "$topology_root" in
+ echo 'rpool raidz1 \'
+ add_zpool_disks
+ IFS=
+ read -r diskidnum
+ echo '/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part3 \'
+ IFS=
+ read -r diskidnum
+ echo '/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part3 \'
+ IFS=
+ read -r diskidnum
+ echo '/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part3 \'
+ IFS=
+ read -r diskidnum
+ sed -i '$s,\\,,' /tmp/rpool_creation.sh
+ echo -e XiaoSon#2020
+ sh /tmp/rpool_creation.sh
invalid vdev specification
the following errors must be manually repaired:
/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part3 is part of active pool 'rpool'
/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part3 is part of active pool 'rpool'
/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part3 is part of active pool 'rpool'

**Comment by jak83A** [comment]
i think here is the problem:

invalid vdev specification
the following errors must be manually repaired:
/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02CW9-part3 is part of active pool 'rpool'
/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02D6T-part3 is part of active pool 'rpool'
/dev/disk/by-id/nvme-Seagate_FireCuda_520_SSD_ZP1000GM30002_7QG02HPM-part3 is part of active pool 'rpool'

**Comment by Sithuk** [comment]
You may just need to destroy (and export I think) the rpool even after you wipe the disks.

sudo zpool destroy rpool
sudo zpool export rpool

Or you could just reboot. That should clear the pool.

**Comment by Sithuk** [comment]
Any update?

**Comment by jak83A** [comment]
Sorry I went to Hospital, will check again when home.

Sithuk ***@***.***> schrieb am Mo. 29. Aug. 2022 um 19:56:
