### ISSUE TITLE
Script dies consistently at `keyboard-configuration`

### ISSUE THREAD

**Issue by andrewvaughan** [Sithuk/ubuntu-server-zfsbootmenu#55]
I've tried running the script multiple times, both with the current LiveUSB image from Ubuntu, and trying an upgrade prior to running. Every time, the script just stops on this line:

https://github.com/Sithuk/ubuntu-server-zfsbootmenu/blob/main/ubuntu_server_encrypted_root_zfs.sh#L1986

No error message, it simply shows:

```
#...
root@ubuntu:/#
root@ubuntu:/# dpkg-reconfigure keyboard-configuration
```

And then returns me to my command prompt. No error messages or any other issues.

I'm unable to run any commands when returned to the prompt. My best guess is that the `dpkg-reconfigure` is creating some type of prompt pop-up and, because it's being run in the new filesystem, it's not being shown to the screen, so the script ends up in some state of limbo where the user can't answer the question but also can't control their terminal any more (however, this is conjecture).

**Comment by Sithuk** [comment]
I have just successfully completed a test run using the script and didn't get any errors for either a 22.04 or 24.04 install.

**Comment by andrewvaughan** [comment]
No worries - I was able to replicate this twice with a LiveUSB key using the latest (24.04.01) download from Ubuntu. Not sure if that might make difference.

I documented my exact steps taken, if curious to run a 1:1 repeat:
https://gist.github.com/andrewvaughan/555910a8d5cdc5eea8bf0e9103d00dd2

(Of course I did everything in the script after it failed manually to complete it).

**Comment by Sithuk** [comment]
Let's close the issue here and track in your other issue thread that has highlighted a bare metal install potentially acting differently than one installed in a VM environment (which is where I have tested).
https://github.com/Sithuk/ubuntu-server-zfsbootmenu/issues/54
