### ISSUE TITLE
Remove the zfs-dkms package?

### ISSUE THREAD

**Issue by w194** [Sithuk/ubuntu-server-zfsbootmenu#7]
I think it would make the kernel update process easier or less error-prone. Would it be possible to remove the `zfs-dkms` package?

**Comment by Sithuk** [comment]
I could do. I think all the Ubuntu lts kernels have zfs integrated. So shouldn’t need it. However, having dkms reduces the risk of an unbootable system if canonical does push out a kernel update without zfs integrated.

**Comment by w194** [comment]
There is also the risk of unbootable system because of failure of dkms while updating. For example when someone updates a HWE kernel and zfs-dkms doesn't support this version.

**Comment by Sithuk** [comment]
The idea with the script is to attempt to keep close to the base ubuntu install defaults. I don't think zfs-dkms is included in the default ubuntu zfs on root install, but I'll check. If it's not, then I'll test removing it from the script and check everything works ok.

**Comment by Sithuk** [comment]
I found a supportive commentary at the following link for removing zfs-dkms.
https://www.reddit.com/r/zfs/comments/klz9xy/is_there_a_need_for_zfsdkms_on_ubuntu_20x_or_later/
"there isn't a need for zfs-dkms on modern Ubuntu, and I don't recommend it."
"modern Ubuntu distros (but not all others) include a ZFS module as part of the shipped kernel, so you don't have to."

**Comment by Sithuk** [comment]
I've commented out the command to install Zfs-dkms.
