### ISSUE TITLE
Remove firewalld for desktop installs

### ISSUE THREAD

**Issue by w194** [Sithuk/ubuntu-server-zfsbootmenu#9]
This package doesn't seem to be needed (isn't included in deskop installs normally) and makes problems

**Comment by Sithuk** [comment]
Thanks for letting me know. You’re right, I don’t think firewalld should be installed. Uncomplicated Firewall (UFW) should be the  default firewall in default Ubuntu installs. Do you know which package is pulling in firewalld?

**Comment by w194** [comment]
> which package is pulling in firewalld?

kubuntu-desktop for me. Not sure why, but I try to find out.

**Comment by Sithuk** [comment]
Adding the --no-install-recommends flag would prevent all the recommended packages being installed for the kubuntu-desktop.

It looks like ufw and firewalld are no longer listed as "recommends" in the latest plasma-firewall package (5.25.4-1ubuntu1).
https://packages.ubuntu.com/source/kinetic/plasma-firewall

Unfortunately there is no mention yet of 5.25 being rolled out to Jammy (22.04):
https://launchpad.net/ubuntu/+source/plasma-firewall

I'm not minded to code a fix for this when it's been corrected upstream. Would a fix be to disable the firewalld service? Is ufw also installed?
sudo systemctl stop firewalld
sudo systemctl disable firewalld

If need be, you can also stop other services from activating it by masking.
sudo systemctl mask firewalld

**Comment by Sithuk** [comment]
Ignore that, there is no change in 5.25.4. Both ufw and firewalld are listed as recommends.
https://packages.ubuntu.com/kinetic/plasma-firewall

What problems are you seeing from having them both installed?

**Comment by Sithuk** [comment]
I just ran a test Kubuntu desktop install with the script. Firewalld is installed, not firewalld and ufw. Plasma-firewall uses firewalld as its backend. I appreciate that is different to the standard Kubuntu install, but there are no problems with the setup that I could see. What problems did you experience? 

Fedora uses firewalld as its default so there should be no issues with using it.

However, I would like the script to stay close to the ubuntu flavour default choices. I've asked upstream why firewalld is installed over ufw when Kubuntu has ufw as its default.

**Comment by w194** [comment]
The problem with firewalld is that it is a bit unexpected that it is installed. For example when I use LXD and I follow their documentation that is mainly written for Ubuntu/ZFS as this is the recommended platform. I need to add some rules to UFW so my containers have network access. 
But this doesn’t work because now I have both UFW and firewalld installed and didn’t know about firewalld and wonder why the container networking isn’t working. 
This is because firewalld blocks eveything even if UFW has it allowed.

**Comment by Sithuk** [comment]
That’s a good example. I raised a question upstream at the following link.
https://answers.launchpad.net/ubuntu/+source/plasma-firewall/+question/703039

However it might not be the plasma-firewall package that is the problem. Perhaps the kubuntu-desktop package should explicitly install ufw, but do it before plasma-firewall is installed?

Could you share your lxd example on the upstream thread I linked above?

**Comment by Sithuk** [comment]
Apparently plasma-firewall is just a copy from upstream Debian. Debian has no default firewall choice so ufw is unlikely to be set as the default in plasma-firewall. I've raised a bug against the kubuntu-desktop package at the link below and pointed out the potential security issue with ufw based scripts not working.
https://bugs.launchpad.net/ubuntu/+source/kubuntu-meta/+bug/1988802 

Unfortunately the kubuntu team has set the issue as a "wishlist" item. I'm not sure where to go with this. The issue is with the upstream package, not the Ubuntu Zfsbootmenu install script. I have little desire to start coding in fixes for upstream bugs.

Could you goto the bug report and add that you are also affected and comment? The additional support might cause the kubuntu team to reconsider the issue.

**Comment by Sithuk** [comment]
Closing here. Bug report raised for upstream package.

**Comment by Sithuk** [comment]
Fix now released upstream.
